# Generated by Django 6.0.1 on 2026-02-25 16:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_variation_color_code_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='color_code',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
