# Generated by Django 6.0.1 on 2026-02-25 19:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_variation_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='hex_code',
        ),
        migrations.AlterField(
            model_name='variation',
            name='color_code',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Color'),
        ),
    ]
