# Generated by Django 6.0.1 on 2026-02-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_alter_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
