# Generated by Django 6.0.1 on 2026-02-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_remove_product_new_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discount',
        ),
    ]
