# Generated by Django 6.0.1 on 2026-03-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_alter_product_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='SubCategory',
        ),
    ]
