# Generated by Django 6.0.1 on 2026-03-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_rename_sub_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
