# Generated by Django 6.0.1 on 2026-03-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_product_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_type',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], verbose_name=1),
        ),
    ]
