# Generated by Django 6.0.1 on 2026-03-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_alter_variation_variation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_type',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=6),
        ),
    ]
