# Generated by Django 6.0.1 on 2026-03-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_alter_variation_variation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_type',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=6, null=True),
        ),
    ]
