# Generated by Django 6.0.1 on 2026-03-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
