# Generated by Django 6.0.1 on 2026-03-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0030_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
