# Generated by Django 6.0.1 on 2026-04-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_shippingfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(default='pickup', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('zipcode', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.order')),
            ],
        ),
    ]
