# Generated by Django 6.0.1 on 2026-04-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0032_order_shipping_type_alter_shippingfee_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=-1989, max_length=255),
            preserve_default=False,
        ),
    ]
