# Generated by Django 6.0.1 on 2026-04-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=11),
            preserve_default=False,
        ),
    ]
