# Generated by Django 6.0.1 on 2026-04-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0034_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(max_length=255),
        ),
    ]
