# Generated by Django 6.0.1 on 2026-04-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0035_alter_order_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
